#!/bin/bash -x

export REPO_TOP=/home/viraphol/prj/siliconforge
PROJ_TOP=$REPO_TOP

VF=$REPO_TOP/bin/VeriForge
LF=$REPO_TOP/bin/LintForge

# run xsim with debugging message
$VF --proj-root $PROJ_TOP/tests/simple --verbose=debug $PROJ_TOP/tests/simple/designs/yang/dv/hello_sim_cfg_xsim.hjson

