#!/bin/bash -x

export REPO_TOP=/home/viraphol/dev/opentitan
export PROJ_TOP=/home/viraphol/prj/siliconforge
dvsim=$REPO_TOP/util/dvsim/dvsim.py

# uncomment to run xsim/vivado
$dvsim --proj-root $PROJ_TOP/tests/simple --scratch-root ./scratch_dvsim $PROJ_TOP/tests/simple/designs/hello/dv/hello_sim_cfg_xsim.hjson


